// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchoolTimetable.Infrastructure;

#nullable disable

namespace SmartSchoolTimetable.Infrastructure.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20261004070614_Phase2FCalendar")]
    partial class Phase2FCalendar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Calendar.CalendarDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AffectsSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("CalendarDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_CalendarDays_Range", "\"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.LocalAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditHistory", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.OwnerAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCustomInactivityTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InactivityTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerSlot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("RecoveryCodeAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecoveryCodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RecoverySalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("OwnerSlot")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentTermId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\" = 1");

                    b.HasIndex("NormalizedLabel")
                        .IsUnique();

                    b.ToTable("AcademicYears", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.BellSettings", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakBell")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BellSettings", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SchoolProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarDisplay")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeralSystem")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleOfficerName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchoolProfile", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StageId", "NormalizedLabel")
                        .IsUnique();

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId", "DisplayOrder");

                    b.HasIndex("AcademicYearId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Stage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId", "DisplayOrder");

                    b.HasIndex("AcademicYearId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.WorkingWeek", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysMask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekStartDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkingWeek", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Subjects.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColorIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DistributionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Heavy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresDoublePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SpreadAcrossDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_ColorIndex", "\"ColorIndex\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Subjects_Priority", "\"Priority\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Teachers.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FullyReleased")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLessonsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLessonsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OffDaysMask")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ReleaseFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("NormalizedFullName");

                    b.HasIndex("NormalizedShortName")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", b =>
                {
                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.Term", "Terms", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<long>("AcademicYearId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("NormalizedName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AcademicYearId", "NormalizedName")
                                .IsUnique();

                            b1.ToTable("Terms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AcademicYearId");
                        });

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SchoolProfile", b =>
                {
                    b.OwnsOne("SmartSchoolTimetable.Domain.SchoolSetup.SchoolAsset", "Logo", b1 =>
                        {
                            b1.Property<long>("SchoolProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("LogoContentType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LogoSizeBytes");

                            b1.Property<string>("StoredFileName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LogoStoredFileName");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("LogoUploadedAt");

                            b1.HasKey("SchoolProfileId");

                            b1.ToTable("SchoolProfile");

                            b1.WithOwner()
                                .HasForeignKey("SchoolProfileId");
                        });

                    b.OwnsOne("SmartSchoolTimetable.Domain.SchoolSetup.SchoolAsset", "Stamp", b1 =>
                        {
                            b1.Property<long>("SchoolProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("StampContentType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StampSizeBytes");

                            b1.Property<string>("StoredFileName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("StampStoredFileName");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("StampUploadedAt");

                            b1.HasKey("SchoolProfileId");

                            b1.ToTable("SchoolProfile");

                            b1.WithOwner()
                                .HasForeignKey("SchoolProfileId");
                        });

                    b.Navigation("Logo");

                    b.Navigation("Stamp");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Section", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Shift", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.LessonPeriod", "Periods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EndBell")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Position")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("ShiftId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("StartBell")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ShiftId", "Position")
                                .IsUnique();

                            b1.ToTable("LessonPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Stage", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Subjects.Subject", b =>
                {
                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.BlockedPeriod", "BlockedPeriods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SubjectId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SubjectId", "Day", "LessonNumber")
                                .IsUnique();

                            b1.ToTable("SubjectBlockedPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });

                    b.Navigation("BlockedPeriods");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Teachers.Teacher", b =>
                {
                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.BlockedPeriod", "BlockedPeriods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("TeacherId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("TeacherId", "Day", "LessonNumber")
                                .IsUnique();

                            b1.ToTable("TeacherBlockedPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeacherId");
                        });

                    b.Navigation("BlockedPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
