// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchoolTimetable.Infrastructure;

#nullable disable

namespace SmartSchoolTimetable.Infrastructure.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Calendar.CalendarDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AffectsSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("CalendarDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_CalendarDays_Range", "\"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Curriculum.CurriculumEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsDoublePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyLessons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StageId", "SubjectId");

                    b.ToTable("CurriculumEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumEntries_WeeklyLessons", "\"WeeklyLessons\" BETWEEN 1 AND 15");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Generation.GenerationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Bound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deterministic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ElapsedSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FirstSolutionSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("Improvements")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonsPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedFromVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LockedLessons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocksDropped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Objective")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Optimal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolverParameters")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolverVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimetableVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Workers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AcademicYearId", "Id");

                    b.ToTable("GenerationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_GenerationRuns_Status", "\"Status\" BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Generation.TimetableVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GenerationRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_TimetableVersions_Approved_Year")
                        .HasFilter("\"IsApproved\" = 1");

                    b.HasIndex("GenerationRunId");

                    b.HasIndex("ParentVersionId");

                    b.HasIndex("AcademicYearId", "Number")
                        .IsUnique();

                    b.ToTable("TimetableVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimetableVersions_ApprovedFlag", "(\"Status\" = 2) = (\"IsApproved\" = 1)");

                            t.HasCheckConstraint("CK_TimetableVersions_Source", "\"Source\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_TimetableVersions_Status", "\"Status\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.LocalAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamsJson")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EventType", "OccurredAt");

                    b.ToTable("AuditHistory", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.OwnerAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCustomInactivityTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InactivityTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerSlot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("RecoveryCodeAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecoveryCodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RecoverySalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("OwnerSlot")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Resources.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Resources", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Capacity", "\"Capacity\" BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Resources_Kind", "\"Kind\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Scheduling.SchedulingProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchedulingProfile", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentTermId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\" = 1");

                    b.HasIndex("NormalizedLabel")
                        .IsUnique();

                    b.ToTable("AcademicYears", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.BellSettings", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakBell")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BellSettings", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SchoolProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarDisplay")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeralSystem")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleOfficerName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchoolProfile", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StageId", "NormalizedLabel")
                        .IsUnique();

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SessionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId")
                        .IsUnique();

                    b.HasIndex("ShiftId");

                    b.ToTable("SessionPlans", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SetupProgress", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedMask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedMask")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SetupProgress", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId", "DisplayOrder");

                    b.HasIndex("AcademicYearId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Stage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DayLessonsSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId", "DisplayOrder");

                    b.HasIndex("AcademicYearId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.WorkingWeek", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysMask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekStartDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkingWeek", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Subjects.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColorIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DistributionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Heavy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RequiredResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresDoublePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SpreadAcrossDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("RequiredResourceId");

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_ColorIndex", "\"ColorIndex\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Subjects_Priority", "\"Priority\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Teachers.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FullyReleased")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLessonsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLessonsPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OffDaysMask")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ReleaseFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("NormalizedFullName");

                    b.HasIndex("NormalizedShortName")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Workload.WorkloadAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurriculumEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumEntryId");

                    b.HasIndex("SectionId", "CurriculumEntryId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkloadAssignments_Active_Section_Entry")
                        .HasFilter("\"IsArchived\" = 0");

                    b.HasIndex("TeacherId", "IsArchived");

                    b.ToTable("WorkloadAssignments", (string)null);
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Curriculum.CurriculumEntry", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Generation.GenerationRun", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Generation.TimetableVersion", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.Generation.GenerationRun", null)
                        .WithMany()
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartSchoolTimetable.Domain.Generation.TimetableVersion", null)
                        .WithMany()
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("SmartSchoolTimetable.Domain.Generation.TimetableLesson", "Lessons", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<long>("CurriculumEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SectionId")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("TeacherId")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("TimetableVersionId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("TimetableVersionId", "SectionId");

                            b1.HasIndex("TimetableVersionId", "TeacherId");

                            b1.ToTable("TimetableLessons", null, t =>
                                {
                                    t.HasCheckConstraint("CK_TimetableLessons_Slot", "\"Day\" BETWEEN 1 AND 7 AND \"LessonNumber\" BETWEEN 1 AND 12");
                                });

                            b1.WithOwner()
                                .HasForeignKey("TimetableVersionId");
                        });

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Scheduling.SchedulingProfile", b =>
                {
                    b.OwnsMany("SmartSchoolTimetable.Domain.Scheduling.SchedulingRule", "Rules", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT");

                            b1.Property<long>("ProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Weight")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("ProfileId", "Key")
                                .IsUnique();

                            b1.ToTable("SchedulingProfileRules", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SchedulingProfileRules_Weight", "\"Weight\" BETWEEN 0 AND 100");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", b =>
                {
                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.Term", "Terms", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<long>("AcademicYearId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("NormalizedName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AcademicYearId", "NormalizedName")
                                .IsUnique();

                            b1.ToTable("Terms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AcademicYearId");
                        });

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SchoolProfile", b =>
                {
                    b.OwnsOne("SmartSchoolTimetable.Domain.SchoolSetup.SchoolAsset", "Logo", b1 =>
                        {
                            b1.Property<long>("SchoolProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("LogoContentType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LogoSizeBytes");

                            b1.Property<string>("StoredFileName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LogoStoredFileName");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("LogoUploadedAt");

                            b1.HasKey("SchoolProfileId");

                            b1.ToTable("SchoolProfile");

                            b1.WithOwner()
                                .HasForeignKey("SchoolProfileId");
                        });

                    b.OwnsOne("SmartSchoolTimetable.Domain.SchoolSetup.SchoolAsset", "Stamp", b1 =>
                        {
                            b1.Property<long>("SchoolProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("StampContentType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StampSizeBytes");

                            b1.Property<string>("StoredFileName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("StampStoredFileName");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("StampUploadedAt");

                            b1.HasKey("SchoolProfileId");

                            b1.ToTable("SchoolProfile");

                            b1.WithOwner()
                                .HasForeignKey("SchoolProfileId");
                        });

                    b.Navigation("Logo");

                    b.Navigation("Stamp");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Section", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.SessionPlan", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.SessionDay", "Days", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Session")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SessionPlanId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Term")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionPlanId", "Term", "Day")
                                .IsUnique();

                            b1.ToTable("SessionDays", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionPlanId");
                        });

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.SessionPeriod", "Periods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Position")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Session")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SessionPlanId")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionPlanId", "Session", "Position")
                                .IsUnique();

                            b1.ToTable("SessionPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionPlanId");
                        });

                    b.Navigation("Days");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Shift", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.LessonPeriod", "Periods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EndBell")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Position")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("ShiftId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("StartBell")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ShiftId", "Position")
                                .IsUnique();

                            b1.ToTable("LessonPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.DayLessons", "DayLessonOverrides", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Lessons")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("ShiftId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("ShiftId", "Day")
                                .IsUnique();

                            b1.ToTable("ShiftDayLessons", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("DayLessonOverrides");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.SchoolSetup.Stage", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.DayLessons", "DayLessonCounts", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Lessons")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("StageId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("StageId", "Day")
                                .IsUnique();

                            b1.ToTable("StageDayLessons", null, t =>
                                {
                                    t.HasCheckConstraint("CK_StageDayLessons_Lessons", "\"Lessons\" >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.Navigation("DayLessonCounts");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Subjects.Subject", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("RequiredResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.BlockedPeriod", "BlockedPeriods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SubjectId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SubjectId", "Day", "LessonNumber")
                                .IsUnique();

                            b1.ToTable("SubjectBlockedPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });

                    b.Navigation("BlockedPeriods");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Teachers.Teacher", b =>
                {
                    b.OwnsMany("SmartSchoolTimetable.Domain.SchoolSetup.BlockedPeriod", "BlockedPeriods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LessonNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("TeacherId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("TeacherId", "Day", "LessonNumber")
                                .IsUnique();

                            b1.ToTable("TeacherBlockedPeriods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeacherId");
                        });

                    b.OwnsMany("SmartSchoolTimetable.Domain.Teachers.TeacherSpecialization", "Specializations", b1 =>
                        {
                            b1.Property<long>("TeacherId")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SubjectId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TeacherId", "SubjectId");

                            b1.HasIndex("SubjectId");

                            b1.ToTable("TeacherSpecializations", (string)null);

                            b1.HasOne("SmartSchoolTimetable.Domain.Subjects.Subject", null)
                                .WithMany()
                                .HasForeignKey("SubjectId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TeacherId");
                        });

                    b.Navigation("BlockedPeriods");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("SmartSchoolTimetable.Domain.Workload.WorkloadAssignment", b =>
                {
                    b.HasOne("SmartSchoolTimetable.Domain.Curriculum.CurriculumEntry", null)
                        .WithMany()
                        .HasForeignKey("CurriculumEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.SchoolSetup.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchoolTimetable.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
